image: node:12.22.0-buster
# image: java:8-jdk

before_script:
    - apt-get update -qy
    - apt-get install -y yarn
    - apt-get install ruby ruby-dev rubygems -y
    # - gem install fastlane -NV
    - gem install dpl
    - yarn install

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_ID --api-key=$HEROKU_API_KEY
