before_script:
    - apt-get update -qy
    - apt-get install -y yarn
    - gem install dpl
    - yarn install

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_ID --api-key=$HEROKU_API_KEY
