before_script:
    - apt-get update -qy
    - apt-get update yarn
    - yarn run build
    - gem install dpl

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_ID --api-key=$HEROKU_API_KEY
    only:
        - staging
