//MESSAGES
export const GET_ERRORS = 'GET_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

//LOADING
export const LOADING = 'LOADING';
export const END_LOADING = 'END_LOADING';
export const CONTINUE_LOADING = 'CONTINUE_LOADING'
